const context = {
    title: "Vide",
    body: "Vide",
    template: [
      {
        shortName: "",
        name: "",
        image_00: "img/xxx/00.jpeg",
        lieu: "",
        ville: "",
        agence: "",
        moa: "",
        preneurs: "",
        amenageur: "",
        partenaires: "",
        programme: "",
        structure : "", 
        facade : "",
        surface : "",
        certifications : "",
        montantTravaux : "",
        role : "",
        phases : "",
        dates: "",
        description: [
      "",
      "",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/xxx/01.jpg",
        image_02: "img/xxx/02.jpg",
        image_03: "img/xxx/03.jpg",
        image_04: "",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "",
        creditPhoto: "",
      },
    ],
    bim: [
      {
        shortName: "BIM",
        name: "",
        image_00: "img/bim/duc/Capture axo.PNG",
        description: [
      "Dès mes premières années d’expérience, j’ai très vite travaillé sur des projets en BIM et plus particulièrement sur le logiciel Revit. Ayant toujours eu un intérêt pour la technologie et les outils informatiques, j’ai très vite adopté ce nouvel outil et ait constamment cherché à approfondir mes connaissances afin que celui-ci serve le projet architectural en assurant une efficacité optimale dans la production des documents graphiques et quantitatifs.",
      "Très rapidement, j’ai occupé le rôle de référent BIM dans les agences où j’ai pu travailler, apportant mon expertise et mes conseils aussi bien sur mes projets que sur le reste des projets de l’agence.",
      "Après 7 ans d’expériences en tant qu’architecte et BIM Manager je bénéficie de cette expérience croisée qui me permet d’identifier dans le détail l’approche de l’utilisation des outils BIM de manière optimale en fonction des besoins et contraintes de chaque projet.",
      "Vous trouverez ci dessous une liste non-exhaustive des tâches que j’ai eu l’occasion de mener sur les projets que j’ai accompagné en BIM. Que ce soit les projets pour lesquels j’occupais également le rôle de chargé de projet, ou bien les projets menés par mes collègues.",
      "",    
  ],
        creditPers: "",
        creditPhoto: "",
      },
    ],
    contact: [
      {
        shortName: "Contact",
        name: "",
        image_00: "img/perso/446391FD-E0B1-412B-85ED-C1766D813547.JPG",
        description: [
      "Dès mes premières années d’expérience, j’ai très vite travaillé sur des projets en BIM et plus particulièrement sur le logiciel Revit. Ayant toujours eu un intérêt pour la technologie et les outils informatiques, j’ai très vite adopté ce nouvel outil et ait constamment cherché à approfondir mes connaissances afin que celui-ci serve le projet architectural en assurant une efficacité optimale dans la production des documents graphiques et quantitatifs.",
      "Très rapidement, j’ai occupé le rôle de référent BIM dans les agences où j’ai pu travailler, apportant mon expertise et mes conseils aussi bien sur mes projets que sur le reste des projets de l’agence.",
      "Après 7 ans d’expériences en tant qu’architecte et BIM Manager je bénéficie de cette expérience croisée qui me permet d’identifier dans le détail l’approche de l’utilisation des outils BIM de manière optimale en fonction des besoins et contraintes de chaque projet.",
      "Vous trouverez ci dessous une liste non-exhaustive des tâches que j’ai eu l’occasion de mener sur les projets que j’ai accompagné en BIM. Que ce soit les projets pour lesquels j’occupais également le rôle de chargé de projet, ou bien les projets menés par mes collègues.",
      "",    
  ],
        creditPers: "",
        creditPhoto: "",
      },
    ],
    duc: [
      {
        shortName: "JAVA",
        name: "Prairie au Duc - ilot J2",
        image_00: "img/duc/00.jpeg",
        lieu: "Prairie au Duc",
        ville: "Nantes",
        agence: "Bond Society",
        moa: "CISN / Nacarat",
        preneurs:"Habitat 44 (bailleur) + Hapi Coop, Solilab, Chessé",
        amenageur: "SAMOA",
        partenaires: "",
        programme: "5000 m² de Logements, 2000 m² de Bureaux, 300 m² de Commerces",
        structure : "structure poteau-poutre bois / poteau-poutre béton", 
        facade : "façade ossature bois (FOB) remplissage béton de chanvre",
        surface : "7 200 m²",
        certifications : "RE2020 - seuil 2025 / Réemploi / FOB béton de chanvre",
        montantTravaux : "17 500 000 € HT",
        role : "Chargé de projet mandataire et coordinateur",
        phases : "ESQ2 APS APD pré-PC PC",
        dates: "Novembre 2022 / Août 2023",
        description: [
      "Le lot J2, répondant au nom de Java, a été remporté par l’agence Bond Society en association avec l’agence allemande Schultearchitekten. Le programme compte, sur une surface totale de 7 117 m2, 69 appartements dont 38 logements locatifs sociaux  (avec parmi eux 10 logements inclusifs qui accompagnent les personnes vulnérables dans leurs projets d’habitats), ainsi que 31 logements en accession libre. Le réseau d’acteurs de l’économie sociale et solidaire Ecossolies occupe 1 860 m2 de surface de bureaux. Enfin, le groupe Chessé, qui gère les cellules commerciales de la Prairie-au-Duc et le food hall Magmaa, commercialisera 300 m2 au rez-de-chaussée.",
      "Le mot-clé est la « décarbonation ». Conçu sur un principe de structure poteau/poutre bois pour la plupar des batiments et béton pour les émergences, le projet fait appel au « béton de chanvre », matériau biosourcé, pour les remplissages de façades. Tous les logements sont desservis par des coursives surdimensionnées et dans lesquelles du mobilier de rangement est aménagé. Sous ce bloc est également prévue la construction d'un parking mutualisé avec les lots voisins accueillant une centaine de places de stationnement, « transformable dans le temps long », selon l’évolution de l’usage de la voiture. Le démarrage du chantier est prévu pour mi-2024 et une livraison à la mi- 2026.",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/duc/01.jpg",
        image_02: "img/duc/02.jpg",
        image_03: "img/duc/03.jpg",
        image_04: "",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "Jeudi Wang",
        creditPhoto: "",
      },
    ],
    pdm2B: [
      {
        shortName: "PDM - 2B",
        name: "Porte de Montreuil - Lot 2B",
        image_00: "img/pdm2B/00.jpeg",
        lieu: "Porte de Montreuil",
        ville: "Paris",
        agence: "Bond Society",
        moa: "Nexity / Crédit Agricole Immobilier / Engie Aire Nouvelle",
        preneurs: "",
        amenageur: "Paris Sud Aménagement",
        partenaires: "",
        programme: "150 chambres en coliving + Café-restaurant",
        structure : "superstructure poteau-poutre bois / socle poteau-poutre béton", 
        facade : "façade ossature bois (FOB) remplissage béton de chanvre",
        surface : "4 500 m² SDP",
        certifications : "RE 2020 E3C2, HQE, Biodiversity",
        montantTravaux : "10 000 000 € HT",
        role : "Chargé de projet",
        phases : "Pré APS / APS / Pré-PC",
        dates: "2020 - 2023",
        description: [
      "Lorem Ipsum",
      "Ipsum lorem",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/xxx/01.jpg",
        image_02: "img/xxx/02.jpg",
        image_03: "img/xxx/03.jpg",
        image_04: "",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "Playtime",
        creditPhoto: "",
      },
    ],
    pdm2D2: [
      {
        shortName: "PDM - 2D2",
        name: "Porte de Montreuil - Lot 2D2",
        image_00: "img/pdm2D2/00.jpeg",
        lieu: "Porte de Montreuil",
        ville: "Paris",
        agence: "Bond Society",
        moa: "Nexity / Crédit Agricole Immobilier / Engie Aire Nouvelle",
        preneurs: "",
        amenageur: "Paris Sud Aménagement",
        partenaires: "",
        programme: "Bureaux réversibles en logements + Foodcourt + Crèche 50 berceaux",
        structure : "Structure poteau-poutre bois / poteau-poutre béton", 
        facade : "Pierre porteuse",
        surface : "13 600 m² SDP",
        certifications : "RE 2020 E3C2, Biodiversity, Breeam, Well",
        montantTravaux : "31 280 000 € HT",
        role : "Chargé de projet",
        phases : "Pré APS / APS / Pré-PC",
        dates: "2020 - 2023",
        description: [
      "",
      "",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/xxx/01.jpg",
        image_02: "img/xxx/02.jpg",
        image_03: "img/xxx/03.jpg",
        image_04: "",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "Playtime",
        creditPhoto: "",
      },
    ],
    charenton: [
      {
        shortName: "CHA",
        name: "Charenton",
        image_00: "img/cha/0130_CHA_COM_JPG_PER1.jpg",
        lieu: "Nouveau quartier de Charenton-Bercy",
        ville: "Charenton-le-Pont",
        agence: "Bond Society",
        moa: "Urbanera / Bouygues Immobilier",
        preneurs: "",
        amenageur: "Grand Paris Aménagement",
        partenaires: "",
        programme: "Coliving, résidences étudiantes et foyer jeune travailleur",
        structure : "", 
        facade : "",
        surface : "25 000 m² SDP",
        certifications : "NF Habitat HQE, RT 2012 -30%, (RE 2020 et E+C- à déterminer)",
        montantTravaux : "39 300 000 € HT",
        role : "Chargé de projet",
        phases : "ESQ APS PC",
        dates: "2021-2022",
        description: [
      "",
      "",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/xxx/01.jpg",
        image_02: "img/xxx/02.jpg",
        image_03: "img/xxx/03.jpg",
        image_04: "",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "Chartier Dalix",
        creditPhoto: "",
      },
    ],
    chanteloup: [
      {
        shortName: "LOU",
        name: "Chanteloup lot A",
        image_00: "img/lou/0141_LOU_COM_PERS PARC BLANC_5MO.jpg",
        lieu: "Nouveau Quartier Rouget de Lisle",
        ville: "Chanteloup-les-Vignes",
        agence: "Bond Society",
        moa: "Priams",
        preneurs: "",
        amenageur: "Paris Sud Aménagement",
        partenaires: "",
        programme: "64 logements + maison médicale + commerce de proximité type boulangerie",
        structure : "", 
        facade : "",
        surface : "5 280 m² SDP",
        certifications : "RE2020 Nf habitat HQE",
        montantTravaux : "7 650 000 € HT",
        role : "Chargé de projet",
        phases : "APS Pré-PC PC",
        dates: "2022-2023",
        description: [
      "",
      "",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/xxx/01.jpg",
        image_02: "img/xxx/02.jpg",
        image_03: "img/xxx/03.jpg",
        image_04: "",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "",
        creditPhoto: "",
      },
    ],
    danton: [
      {
        shortName: "DAN",
        name: "Danton",
        image_00: "img/dan/HARVEY-HAVRE_V03_2.jpg",
        lieu: "Rue Michelet",
        ville: "Le Havre",
        agence: "Bond Society",
        moa: "Harvey",
        preneurs: "",
        amenageur: "",
        partenaires: "",
        programme: "Résidence de coliving sportif (127 logements) + Dojo + Restaurant + Coworking",
        structure : "", 
        facade : "",
        surface : "5 421 m² SDP",
        certifications : "RE 2020 / NF Habitat HQE très performant / Biodiversita",
        montantTravaux : "",
        role : "Chargé de projet",
        phases : "ESQ APS PC",
        dates: "2022 - 2023",
        description: [
      "",
      "",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/xxx/01.jpg",
        image_02: "img/xxx/02.jpg",
        image_03: "img/xxx/03.jpg",
        image_04: "",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "Fiction Studio",
        creditPhoto: "",
      },
    ],
    bussy: [
      {
        shortName: "BUS",
        name: "Groupe Scolaire de 22 classes et Centre périscolaire",
        image_00: "img/xxx/00.jpeg",
        lieu: "Allée Madame de Montespan",
        ville: "Bussy-Saint-Georges",
        agence: "Bond-Society",
        moa: "Ville de Bussy-Saint-Georges",
        preneurs: "",
        amenageur: "",
        partenaires: "Daudré-Vignier & Associés (mand.)",
        programme: "Construction neuve d'un groupe scolaire 22 classes + Centre de loisirs + Restaurant scolaire",
        structure : "Structure poteau-poutre bois", 
        facade : "Façade ossature bois (FOB) remplissage biosourcé",
        surface : "5 696 m² SDP",
        certifications : "Construction bois, E3C2, BBC Effinergie 2017, Label Bâtiment Biosourcé Niveau 3, HQE Bâtiment Durable Très performant",
        montantTravaux : "12 940 550 € HT",
        role : "Chargé de projet",
        phases : "ESQ",
        dates: "2020",
        description: [
      "",
      "",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/xxx/01.jpg",
        image_02: "img/xxx/02.jpg",
        image_03: "img/xxx/03.jpg",
        image_04: "",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "",
        creditPhoto: "",
      },
    ],
    drancy: [
      {
        shortName: "DRA",
        name: "L'école Simone de Beauvoir",
        image_00: "img/dra/0062_DRA_COM_PHOTO_26_LDD.jpg",
        lieu: "Rue Jacqueline Quatremaire",
        ville: "Drancy",
        agence: "Bond Society",
        moa: "Ville de Drancy ",
        preneurs: "",
        amenageur: "",
        partenaires: "Daudré-Vignier & Associés (mand.)",
        programme: "Construction neuve d'un groupe scolaire élémentaire + Restaurant scolaire",
        structure : "Structure poteau-poutre bois", 
        facade : "Façade ossature bois (FOB) remplissage biosourcé",
        surface : "2 100 m² SDP",
        certifications : "RT 2012",
        montantTravaux : "5 800 000 € HT",
        role : "Chargé de projet",
        phases : "DET",
        dates: "2020",
        description: [
      "",
      "",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/dra/0062_DRA_COM_PHOTO_17.JPG",
        image_02: "img/dra/0062_DRA_COM_PHOTO_14.JPG",
        image_03: "img/dra/0062_DRA_COM_PHOTO_11.JPG",
        image_04: "img/dra/0062_DRA_COM_PHOTO_4.JPG",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "",
        creditPhoto: "Charly Broyer + Bond Society + Adelly Lau",
      },
    ],
    strasbourg: [
      {
        shortName: "STR",
        name: "MELT Hôtel - Strasbourg Ban de la Roche",
        image_00: "img/str/0122_BAN_COM_JPG_PER_EXT RUE.jpg",
        lieu: "Rue du ban de la roche",
        ville: "Strasbourg",
        agence: "Bond Society",
        moa: "MELT, Altarea Cogedim",
        preneurs: "",
        amenageur: "",
        partenaires: "O Architecture (mand.)",
        programme: "Hôtel, Foodcourt et Rooftop",
        structure : "", 
        facade : "",
        surface : "4823 m²",
        certifications : "",
        montantTravaux : "",
        role : "Chargé de projet",
        phases : "ESQ APS",
        dates: "2020-2021",
        description: [
      "",
      "",
  ],
        tachesProjet: [
          "Participation aux réunions internes MOE",
          "Participation aux réunions MOA",
        ],
        tachesBim: [
          "xx",
          "xx",
        ],
        image_01: "img/str/0122_BAN_COM_JPG_PER_ ATTIQUE.jpg",
        image_02: "img/str/0122_BAN_COM_PDF_PLA_100_Zoning convivialité_page-0001.jpg",
        image_03: "img/str/0122_BAN_COM_JPG_SKE_axonomÇtrie site dÇsaturÇ.jpg",
        image_04: "img/str/0122_BAN_COM_JPG_PLA_Plan masse zoom.jpg",
        image_05: "",
        image_06: "",
        image_07: "",
        image_08: "",
        image_09: "",
        image_10: "",
        image_11: "",
        image_12: "",
        image_13: "",
        image_14: "",
        image_15: "",
        image_16: "",
        image_17: "",
        image_18: "",
        image_19: "",
        image_20: "",
        creditPers: "O architecture",
        creditPhoto: "",
      },
    ],
    
  };
  
  // Formule handlebar template
  
  const templateElement = document.getElementById("templateHB");
  
  const templateSource = templateElement.innerHTML;
  
  const template = Handlebars.compile(templateSource);
  
  const compiledHtml = template(context);
  
  document.getElementById("informations").innerHTML = compiledHtml;
  
  